name: Codecov

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Run install dependencies
      run: sudo apt-add-repository ppa:mutlaqja/ppa -y && sudo apt update && sudo apt upgrade -y && sudo apt install libgl-dev libspdlog-dev libboost-dev libgsl-dev libcfitsio-dev libcurl4-openssl-dev libz-dev python3-dev libopencv-dev libssl-dev libsqlite3-dev libboost-system-dev libboost-thread-dev && sudo apt-get install libindi1 libev-dev indi-bin libindi-dev

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}



